openapi: 3.0.3
info:
  title: Meteored Weather Forecast API Free
  description: Official documentation for location search, daily and hourly weather forecasts.
  version: 1.0.0
servers:
  - url: https://api.meteored.com
    description: Base URL
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    ErrorResponse:
      type: object
      properties:
        ok:
          type: boolean
          example: false
        expiracion:
          type: integer
          example: 1780714391270
        info:
          type: object
          properties:
            message:
              type: string
              example: Bad Request
security:
  - ApiKeyAuth: []
paths:
  /api/location/v1/search/txt/{text}:
    get:
      summary: Location search by text
      description: Search for a location by its text name to retrieve its hash.
      parameters:
        - name: text
          in: path
          required: true
          schema:
            type: string
          description: Location text
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          description: API Key
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                ok: true
                data:
                  locations:
                    - hash: 2f221a18eb86380369570b2ed147d8b4
                      name: Almendricos
                      description: Murcia
                      country_name: Spain
                expiracion: 1701758778968
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/forecast/v1/daily/{hash}:
    get:
      summary: Location daily forecast for the next 5 days.
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
          description: Location hash
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          description: API Key
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                ok: true
                data:
                  url: https://www.theweather.com/lorca-in-spain-c4513.htm
                  hash: 994007b68e592e9227025715c0c3cb45
                  name: Lorca
                  rain: 0
                  start: 1701730800000
                  sun_in: 1701759984000
                  symbol: 4
                  moon_in: 1701732496000
                  sun_mid: 1701777436000
                  sun_out: 1701794875000
                  humidity: 72
                  moon_out: 1701780616000
                  pressure: 1019
                  snowline: 2700
                  wind_gust: 26
                  wind_speed: 12
                  moon_symbol: 21
                  uv_index_max: 1.9
                  wind_direction: SE
                  temperature_max: 16.56
                  temperature_min: 3.32
                  rain_probability: 20
                  moon_illumination: 47.97
                expiracion: 1701772393000
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/forecast/v1/hourly/{hash}:
    get:
      summary: Location hourly forecast for today.
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
          description: Location hash
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          description: API Key
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                ok: true
                data:
                  url: https://www.theweather.com/lorca-in-spain-c4513.htm
                  hash: 994007b68e592e9227025715c0c3cb45
                  name: Lorca
                  start: 1701730800000
                  hours:
                    - end: 1701734400000
                      rain: 0
                      night: true
                      clouds: 46
                      symbol: 3
                      humidity: 93
                      pressure: 1019
                      snowline: 3100
                      wind_gust: 16
                      wind_speed: 7
                      temperature: 7.78
                      uv_index_max: 0
                      wind_direction: NW
                      rain_probability: 0
                      temperature_feels_like: 6.87
                expiracion: 1701772393000
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
